# DigitalOcean Playbook
---
- name: DigitalOcean
  hosts: localhost
  connection: local
  gather_facts: False

  tasks:

  - name: include variables
    include_vars: vars/droplet.yml

  - name: Confirm SSH key is present
    digital_ocean_sshkey:
      state: present
      name: "{{ ssh_key_name }}"
      ssh_pub_key: "{{ droplet_ssh_key }}"
      oauth_token: "{{ digital_ocean_api_token }}"

  - name: Remove SSH key
    digital_ocean_sshkey:
      state: absent
      name: "{{ ssh_key_name }}"
      ssh_pub_key: "{{ droplet_ssh_key }}"
      oauth_token: "{{ digital_ocean_api_token }}"
